first
NourSammour/biletiniz pull request #11
Opened 2019-07-20 11:32 UTC by LamaDabbeet

2019-07-20 14:09 UTC, NourSammour requested changes
Ohh, no
why did you add `hello-world` folder? you should keep the code but without that folder
instead of `hello-world/package.json` you should use `package.json`

2019-07-20 20:27 UTC, LamaDabbeet commented
after request changes

2019-07-21 06:38 UTC, LamaDabbeet commented
It was merged successfully before adding .gitignore , but after adding it , the automatic merge was not  applicable, should I push a version without .gitignore ??

2019-07-21 07:47 UTC, NourSammour requested changes

2019-07-21 07:47 UTC, NourSammour commented on package-lock.json
> +{
please remove this file, later we will use yarn - not npm -

2019-07-21 08:07 UTC, LamaDabbeet commented
I have remove the. gitignore

2019-07-21 08:18 UTC, NourSammour requested changes

2019-07-21 08:18 UTC, NourSammour commented on .gitignore
> -/node_modules
Why did you remove `.gitignore`, we should keep it ?

2019-07-21 08:18 UTC, NourSammour requested changes

2019-07-21 08:18 UTC, NourSammour commented on package.json
> -  "description": "Uygun uçak bileti Nereye isterseniz | Biletiniz.com",
`  "description": "Uygun uçak bileti Nereye isterseniz | Biletiniz.com",`
please keep description

2019-07-21 08:31 UTC, LamaDabbeet commented on package.json
> -  "description": "Uygun uçak bileti Nereye isterseniz | Biletiniz.com",
done

2019-07-21 08:31 UTC, LamaDabbeet commented on .gitignore
> -/node_modules
done

2019-07-21 08:37 UTC, NourSammour approved these changes

2019-07-21 08:38 UTC, merged