Adding React dependency
NourSammour/biletiniz pull request #13
Opened 2019-07-20 13:35 UTC by MohammadSommakia

2019-07-20 13:49 UTC, NourSammour requested changes
node_modules should be ignored, please add it to .gitignore file
or rebase your fork, @AbdilFattahBoshi already did that
https://github.com/NourSammour/biletiniz/pull/12

2019-07-20 15:05 UTC, MohammadSommakia commented
Sorry i forgot to put it in ignore file and  i create it
 without reading that Abdil Fattah did that.

2019-07-20 17:12 UTC, NourSammour requested changes

2019-07-20 17:12 UTC, NourSammour commented on package-lock.json
> +{
while we are using `yarn` we should not use `package-lock`
please remove this file

2019-07-21 07:45 UTC, NourSammour requested changes
again i see node_modules files, please ignore it

2019-07-21 15:05 UTC, closed without merging