adding pre-commit hook with eslint checking and prettier format
NourSammour/biletiniz pull request #22
Opened 2019-07-21 17:14 UTC by MohammadSommakia

2019-07-21 21:18 UTC, NourSammour requested changes
your task is related to pre-commit
so why you did changes in react version and bugs urls

2019-07-22 13:40 UTC, NourSammour requested changes
fix confilcts

2019-07-23 04:20 UTC, MohammadSommakia commented
sorry about that but I did not pay attention

2019-07-23 14:47 UTC, NourSammour requested changes

2019-07-23 14:47 UTC, NourSammour commented on package.json
> +   "dependencies": {
please revert this space

2019-07-25 13:35 UTC, closed without merging