Dotenv Var #2
NourSammour/biletiniz pull request #26
Opened 2019-07-22 19:56 UTC by LamaDabbeet

2019-07-23 08:21 UTC, NourSammour requested changes

2019-07-23 08:21 UTC, NourSammour commented on server.js
> -const express = require('express')
we should use both dot-env and express server, why did you remove it

2019-07-23 10:11 UTC, LamaDabbeet commented on server.js
> -const express = require('express')
I have merged both dot-env and express server.

2019-07-23 19:25 UTC, NourSammour commented on pages/about.js
> -export default () => <div>About us</div>
why did you remove this files?

2019-07-23 21:40 UTC, LamaDabbeet commented on pages/about.js
> -export default () => <div>About us</div>
I have added it

2019-07-24 10:10 UTC, NourSammour requested changes

2019-07-24 10:10 UTC, NourSammour commented on pages/day/index.js
> -export default () => <div>Hello Day</div>
why did you remove this?

2019-07-24 21:33 UTC, NourSammour approved these changes

2019-07-24 21:33 UTC, merged