Deployment with env variables
NourSammour/biletiniz pull request #30
Opened 2019-07-24 20:24 UTC by LamaDabbeet

2019-07-24 21:32 UTC, NourSammour requested changes

2019-07-24 21:32 UTC, NourSammour commented on pages/index.js.orig
> +>>>>>>> 1063356d6cf9ab1a090cdbfdd7a1fdc6a15945f2
merge issue

2019-07-24 21:32 UTC, NourSammour commented on pages/index.js.orig
> +<<<<<<< HEAD
merge issue

2019-07-24 21:32 UTC, NourSammour commented on pages/index.js.orig
> +=======
merge issue

2019-07-24 21:32 UTC, NourSammour commented on next.config.js
> +console.log({
i prefer to keep using .env file

2019-07-25 08:55 UTC, LamaDabbeet commented
I resolve the issues

2019-07-25 09:17 UTC, NourSammour approved these changes

2019-07-25 09:17 UTC, merged