Adding  pre-commit hook with eslint checking and prettier format And testing it
NourSammour/biletiniz pull request #33
Opened 2019-07-25 13:36 UTC by MohammadSommakia

2019-07-25 20:48 UTC, NourSammour requested changes

2019-07-25 20:48 UTC, NourSammour commented on pages/a.js.rej
> +diff a/pages/a.js b/pages/a.js	(rejected hunks)
What is this?

2019-07-25 20:48 UTC, NourSammour commented on stories/index.js.rej
> +diff a/stories/index.js b/stories/index.js	(rejected hunks)
What is this?

2019-07-25 20:48 UTC, NourSammour commented on stories/index.js
> +  background: #fafafabb;
Why you did changes here?

2019-07-26 06:15 UTC, MohammadSommakia commented
i did not any changes eccept package.json

2019-07-26 10:27 UTC, MohammadSommakia commented on pages/a.js.rej
> +diff a/pages/a.js b/pages/a.js	(rejected hunks)
it is generated files i will delete them then i will push

2022-06-12 09:18 UTC, closed without merging